language: generic 

sudo: require

services:
    - docker

before_install:
    - docker build -t somranjan87/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true USERNAME/docker-react npm run test    
